# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 120, 16))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 25, 621, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.raw_image_viewer = QtWidgets.QLabel(self.layoutWidget)
        self.raw_image_viewer.setMouseTracking(True)
        self.raw_image_viewer.setText("")
        self.raw_image_viewer.setScaledContents(True)
        self.raw_image_viewer.setObjectName("raw_image_viewer")
        self.horizontalLayout_4.addWidget(self.raw_image_viewer)
        self.result_viewer = QtWidgets.QLabel(self.layoutWidget)
        self.result_viewer.setMouseTracking(True)
        self.result_viewer.setText("")
        self.result_viewer.setScaledContents(True)
        self.result_viewer.setObjectName("result_viewer")
        self.horizontalLayout_4.addWidget(self.result_viewer)
        self.exposure_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.exposure_comboBox.setGeometry(QtCore.QRect(11, 406, 114, 19))
        self.exposure_comboBox.setObjectName("exposure_comboBox")
        self.exposure_comboBox.addItem("")
        self.exposure_comboBox.addItem("")
        self.exposure_value = QtWidgets.QLineEdit(self.centralwidget)
        self.exposure_value.setGeometry(QtCore.QRect(131, 406, 131, 19))
        self.exposure_value.setObjectName("exposure_value")
        self.exposure_button = QtWidgets.QPushButton(self.centralwidget)
        self.exposure_button.setGeometry(QtCore.QRect(268, 404, 75, 23))
        self.exposure_button.setObjectName("exposure_button")
        self.show_image_button = QtWidgets.QPushButton(self.centralwidget)
        self.show_image_button.setGeometry(QtCore.QRect(11, 436, 75, 23))
        self.show_image_button.setObjectName("show_image_button")
        self.cc_detect_button = QtWidgets.QPushButton(self.centralwidget)
        self.cc_detect_button.setGeometry(QtCore.QRect(93, 436, 75, 23))
        self.cc_detect_button.setObjectName("cc_detect_button")
        self.calibration_button = QtWidgets.QPushButton(self.centralwidget)
        self.calibration_button.setGeometry(QtCore.QRect(174, 436, 75, 23))
        self.calibration_button.setObjectName("calibration_button")
        self.quick_calibration_button = QtWidgets.QPushButton(self.centralwidget)
        self.quick_calibration_button.setGeometry(QtCore.QRect(255, 436, 75, 23))
        self.quick_calibration_button.setObjectName("quick_calibration_button")
        self.save_image_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_image_button.setGeometry(QtCore.QRect(336, 436, 75, 23))
        self.save_image_button.setAutoDefault(True)
        self.save_image_button.setObjectName("save_image_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Hello PyQt Designer!"))
        self.exposure_comboBox.setItemText(0, _translate("MainWindow", "auto_exposure"))
        self.exposure_comboBox.setItemText(1, _translate("MainWindow", "manual_exposure"))
        self.exposure_button.setText(_translate("MainWindow", "确定"))
        self.show_image_button.setText(_translate("MainWindow", "播放"))
        self.cc_detect_button.setText(_translate("MainWindow", "色卡检测"))
        self.calibration_button.setText(_translate("MainWindow", "标定"))
        self.quick_calibration_button.setText(_translate("MainWindow", "一键标定"))
        self.save_image_button.setText(_translate("MainWindow", "保存图像"))
