# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'correction.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 120, 16))
        self.label.setObjectName("label")
        self.exposure_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.exposure_comboBox.setGeometry(QtCore.QRect(11, 406, 114, 19))
        self.exposure_comboBox.setObjectName("exposure_comboBox")
        self.exposure_comboBox.addItem("")
        self.exposure_comboBox.addItem("")
        self.exposure_value = QtWidgets.QLineEdit(self.centralwidget)
        self.exposure_value.setGeometry(QtCore.QRect(131, 406, 131, 19))
        self.exposure_value.setObjectName("exposure_value")
        self.exposure_button = QtWidgets.QPushButton(self.centralwidget)
        self.exposure_button.setGeometry(QtCore.QRect(268, 404, 75, 23))
        self.exposure_button.setObjectName("exposure_button")
        self.show_image_button = QtWidgets.QPushButton(self.centralwidget)
        self.show_image_button.setGeometry(QtCore.QRect(11, 436, 75, 23))
        self.show_image_button.setObjectName("show_image_button")
        self.cc_wb_button = QtWidgets.QPushButton(self.centralwidget)
        self.cc_wb_button.setGeometry(QtCore.QRect(93, 436, 75, 23))
        self.cc_wb_button.setObjectName("cc_wb_button")
        self.wp_wb_button = QtWidgets.QPushButton(self.centralwidget)
        self.wp_wb_button.setGeometry(QtCore.QRect(174, 436, 75, 23))
        self.wp_wb_button.setObjectName("wp_wb_button")
        self.correction_button = QtWidgets.QPushButton(self.centralwidget)
        self.correction_button.setGeometry(QtCore.QRect(255, 436, 75, 23))
        self.correction_button.setObjectName("correction_button")
        self.save_image_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_image_button.setGeometry(QtCore.QRect(336, 436, 75, 23))
        self.save_image_button.setAutoDefault(True)
        self.save_image_button.setObjectName("save_image_button")
        self.raw_image_viewer = QtWidgets.QLabel(self.centralwidget)
        self.raw_image_viewer.setGeometry(QtCore.QRect(10, 26, 281, 271))
        self.raw_image_viewer.setMouseTracking(True)
        self.raw_image_viewer.setText("")
        self.raw_image_viewer.setScaledContents(True)
        self.raw_image_viewer.setObjectName("raw_image_viewer")
        self.result_viewer = QtWidgets.QLabel(self.centralwidget)
        self.result_viewer.setGeometry(QtCore.QRect(373, 26, 291, 271))
        self.result_viewer.setMouseTracking(True)
        self.result_viewer.setText("")
        self.result_viewer.setScaledContents(True)
        self.result_viewer.setObjectName("result_viewer")
        self.multilight_wp_wb_button = QtWidgets.QPushButton(self.centralwidget)
        self.multilight_wp_wb_button.setGeometry(QtCore.QRect(170, 460, 75, 23))
        self.multilight_wp_wb_button.setObjectName("multilight_wp_wb_button")
        self.multilight_correction_button = QtWidgets.QPushButton(self.centralwidget)
        self.multilight_correction_button.setGeometry(QtCore.QRect(250, 460, 75, 23))
        self.multilight_correction_button.setObjectName("multilight_correction_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Hello PyQt Designer!"))
        self.exposure_comboBox.setItemText(0, _translate("MainWindow", "auto_exposure"))
        self.exposure_comboBox.setItemText(1, _translate("MainWindow", "manual_exposure"))
        self.exposure_button.setText(_translate("MainWindow", "确定"))
        self.show_image_button.setText(_translate("MainWindow", "播放"))
        self.cc_wb_button.setText(_translate("MainWindow", "色卡光源预测"))
        self.wp_wb_button.setText(_translate("MainWindow", "白纸光源预测"))
        self.correction_button.setText(_translate("MainWindow", "矫正"))
        self.save_image_button.setText(_translate("MainWindow", "保存图像"))
        self.multilight_wp_wb_button.setText(_translate("MainWindow", "多光源预测"))
        self.multilight_correction_button.setText(_translate("MainWindow", "多光源矫正"))



